language: cpp
os: linux

jobs:
    include:
        - os: linux
          dist: focal
          compiler: g++
          addons:
            apt:
              packages:
                - cmake
              
install:
  - echo "Install"

before_script:
  - mkdir -p build && cd build
  - cmake ..
    
script:
  - echo "After Script"
    
after_success:
 - echo 
