language: cpp
os: linux

jobs:
    include:
        - os: linux
          dist: focal
          compiler: g++
          addons:
            apt:
              packages:
                - cmake
                - git
                - g++
                - libboost-program-options-dev
                - libboost-filesystem-dev
                - doxygen
                - graphviz
                - bison
                - zlib1g-dev
              
install:
  - echo "Install"

before_script:
  - mkdir -p build && cd build
  - cmake ..
    
script:
  - echo "After Script"
    
after_success:
 - echo 
