language: cpp
os: linux
sudo: required

jobs:
    include:
        - os: linux
          dist: focal
          UBUNTU=true
          compiler: g++
          addons:
            apt:
              packages:
                - cmake
                - git
                - g++
                - libboost-program-options-dev
                - libboost-filesystem-dev
                - doxygen
                - graphviz
                - bison
                - zlib1g-dev
                - python2-dev
                - python-numpy
                - z3
                - libz3-dev
                - libjsoncpp-dev
                - libsqlite3-dev
				- protoc
				- libprotobuf-dev
        - os: linux
          UBUNTU=false
          services: docker
          
        
                
install:
  - echo "Install"

before_script:
  - mkdir -p build && cd build
  - cmake ..

script:
  - make
    
after_success:
 - echo "Done"
