language: cpp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env: 
  global: 
  
matrix:
  include:
    - os: linux
      dist: ubuntu-latest
      compiler: g++
      addons:
        apt:
         sources:
             sourceline: 'ppa:ubuntu-toolchain-r/universe'
             packages:
              - cmake
              - git
              - g++
              - libboost-program-options-dev
              - libboost-filesystem-dev
              - python2-dev
              - doxygen
              - graphviz
              - bison
              - zlib1g-dev
              - python-numpy
              
install:
  - echo "Install"

before_script:
  - mkdir -p build && cd build
  - cmake ..
    
script:
  - echo "After Script"
    
after_success:
 - echo 



       
